version: '3.8'
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: operationsboardcontainer  # Container name
      build: ./frontend/ # Location of our Dockerfile
      volumes: # Volume binding
        - './frontend/:/usr/src/app'
      ports:
        - '4200:4200' # Port mapping
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"


# Pimcore Bakcend
    redis:
        image: redis:alpine
        command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]

    db:
        image: mariadb:10.7
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1]
        volumes:
            - ./operationsBoardBackend/pimcore-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./operationsBoardBackend:/var/www/html:ro
            - ./operationsBoardBackend/.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:php8.1-debug-latest
        environment:
            COMPOSER_HOME: /var/www/html
            PHP_IDE_CONFIG: serverName=localhost
        depends_on:
            - db
        volumes:
            - ./operationsBoardBackend:/var/www/html

    supervisord:
        user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:php8.1-supervisord-latest
        depends_on:
            - db
        volumes:
            - ./operationsBoardBackend:/var/www/html
            - ./operationsBoardBackend/.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro

volumes:
    pimcore-database:
