version: '3.8'
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: operationsboardcontainer  # Container name
      build: ./frontend/ # Location of our Dockerfile
      volumes: # Volume binding
        - './frontend/:/usr/src/app'
      ports:
        - '4200:4200' # Port mapping
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"