version: '3.8'
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: operationsboardcontainer  # Container name
      build: ./frontend/ # Location of our Dockerfile
      volumes: # Volume binding
        - './frontend/:/usr/src/app'
      ports:
        - '4200:4200' # Port mapping
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    db:
        image: mariadb:latest
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_pw
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql
    api:
        container_name: php_web
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - db:db_server
        ports:
            - "80:80"
        working_dir: /var/www/html/
        stdin_open: true
        tty: true
        volumes:
            - ./backend:/var/www/
            - ./database:/var/lib/mysql
    operationboard-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: operationboard-phpmyadmin
        depends_on:
            - db
        links:
            - db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
            MYSQL_ROOT_PASSWORD: my_secret_pw